# Generated by Django 6.0 on 2025-12-24 04:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0, help_text='Value in app currency')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.CharField(blank=True, max_length=2, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('about', models.TextField(default='Not set')),
                ('hopes', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(default='Not set', max_length=50)),
                ('twitter', models.CharField(default='Not set', max_length=50)),
                ('instagram', models.CharField(default='Not set', max_length=50)),
                ('facebook', models.CharField(default='Not set', max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('online', models.BooleanField(default=False)),
                ('promoted', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=False)),
                ('modify', models.IntegerField(default=0)),
                ('subscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_subscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_shows', models.IntegerField(default=0)),
                ('referal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promoter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user_images', models.JSONField(blank=True, null=True)),
                ('user_interests', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('supabase_id', models.CharField(blank=True, max_length=255, null=True)),
                ('supabase_email', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('mno_transaction_reference', models.CharField(blank=True, max_length=255)),
                ('issued_receipt_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='operations.user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_global', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for global notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.JSONField(blank=True, help_text='Array of image URLs', null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('total_gifts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='operations.user')),
            ],
            options={
                'verbose_name': 'Moment',
                'verbose_name_plural': 'Moments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('is_image', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('gift', models.BooleanField(default=False)),
                ('gift_image', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='operations.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='operations.user')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='operations.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.moment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='operations.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='operations.user')),
            ],
            options={
                'verbose_name': 'User Gift',
                'verbose_name_plural': 'User Gifts',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default='Not yet set', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='operations.user')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superlike', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='operations.user')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_liked', to='operations.user')),
            ],
            options={
                'verbose_name': 'Profile Like',
                'verbose_name_plural': 'Profile Likes',
                'unique_together': {('liker', 'liked_user')},
            },
        ),
        migrations.CreateModel(
            name='MomentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='operations.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to='operations.user')),
            ],
            options={
                'verbose_name': 'Moment Like',
                'verbose_name_plural': 'Moment Likes',
                'unique_together': {('moment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_by_user1', models.BooleanField(default=False)),
                ('seen_by_user2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='operations.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='operations.user')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
