# Generated by Django 6.0 on 2025-12-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('operations', '0002_auto_20251224_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='engagement_score',
            field=models.FloatField(default=0, help_text='Overall user engagement score'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_recommendation_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recommendation_boost',
            field=models.FloatField(default=1.0, help_text='Boost factor for recommendations'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('scrolled_to_bottom', models.BooleanField(default=False)),
                ('viewed_images_count', models.IntegerField(default=0)),
                ('clicked_social_links', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile View',
                'verbose_name_plural': 'Profile Views',
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_preference_min', models.IntegerField(default=18)),
                ('age_preference_max', models.IntegerField(default=99)),
                ('distance_importance', models.FloatField(default=0.5)),
                ('activity_level_preference', models.FloatField(default=0.5)),
                ('avg_session_duration', models.IntegerField(default=0, help_text='Average session in seconds')),
                ('preferred_time_of_day', models.CharField(default='evening', max_length=20)),
                ('swipe_rate', models.FloatField(default=0)),
                ('response_rate', models.FloatField(default=0)),
                ('total_engagement_score', models.FloatField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('interest_weights', models.JSONField(default=dict, help_text='Interest preference weights')),
                ('personality_vector', models.JSONField(default=dict, help_text='Personality compatibility vector')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference Profile',
                'verbose_name_plural': 'User Preference Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('profile_view', 'Profile View'), ('like', 'Like'), ('superlike', 'Superlike'), ('pass', 'Pass'), ('message_sent', 'Message Sent'), ('moment_view', 'Moment View'), ('moment_like', 'Moment Like'), ('comment', 'Comment'), ('gift_sent', 'Gift Sent')], max_length=50)),
                ('engagement_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type', '-created_at'], name='operations__user_id_ccd86c_idx')],
            },
        ),
    ]
