# Generated by Django 4.2.7 on 2026-01-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
