# Generated by Django 4.2.7 on 2026-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_phoneotp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_page',
            field=models.PositiveIntegerField(default=1, help_text='Current page in users list pagination'),
        ),
    ]
